### ISSUE TITLE
ACCESSSIBILITY Branch

### ISSUE THREAD

**Issue by axcell-0** [prg-04/My_Portfolio#9]
If you like what you see thanks for leaving a star.
And if there is something to improve please your comment will be highly awaited Thanks in advance.

**Comment by ProgramKingAbel** [comment]
Clean code and well-structured. 
Nice job. keep up and happy coding.

**Comment by axcell-0** [comment]
excellent correction of your code continue to improve nice structure and clean code nice job 😁👌😊
